# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  buildBranch:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build
      - run:
          name: publish coverage
          command: ./gradlew sendCoverageToCodacy
  buildMaster:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build
      - run:
          name: Set version
          command: |
            echo 'export ORG_GRADLE_PROJECT_version="$(./gradlew -q printVersion)"' >> $BASH_ENV
      - run:
          name: Upload
          command: ./gradlew bintrayUpload
workflows:
  version: 2
  buld-deploy:
    jobs:
      - buildBranch:
          filters:
            branches:
              ignore: master
      - buildMaster:
          filters:
            branches:
              only: master
