# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  buildBranch:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build
  buildMaster:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build
      - run:
          name: Set git tag
          command: ./gradlew tagVersion && git push --tags
workflows:
  version: 2
#  feature-branch:
#    jobs:
#      - buildBranch:
#          filters:
#            branches:
#              ignore: master
  master-branch:
    jobs:
      - buildMaster
#          filters:
#            branches:
#              only: master
