# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  buildBranch:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build
  buildMaster:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew build
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Set directory name
          command: BINTRAY_LOC='abwilkinson/discord-spring-starter/discord-spring-starter-release/'"$(./gradlew -q printVersion)"
      - run:
          name: Upload
          command: |
            ./jfrog bt config --user $BINTRAY_USER --key $BINTRAY_KEY --interactive=false
            ./jfrog bt u "./build/libs/*.jar" 'abwilkinson/discord-spring-starter/discord-spring-starter-release/'"$(./gradlew -q printVersion)"
workflows:
  version: 2
#  feature-branch:
#    jobs:
#      - buildBranch:
#          filters:
#            branches:
#              ignore: master
  master-branch:
    jobs:
      - buildMaster
#          filters:
#            branches:
#              only: master
